export { default as PokemonLogo } from "./svgs/pokeball-pokemon-logo.svg";
export { default as RippleLoader } from "./svgs/ripple-loader.svg";
export { default as TickIcon } from "./svgs/tick.svg";
export { default as CloseIcon } from "./svgs/close-circle.svg";
export { default as SortUpIcon } from "./svgs/sort-amount-up.svg";
export { default as SortDownIcon } from "./svgs/sort-amount-down.svg";
export { default as PikachuError } from "./gifs/pikachu-error.gif";
export { default as PikachuEatingGif } from "./gifs/pokemon-eating.gif";
export { default as NoCaughtPokemonsGif } from "./gifs/no-caught-pokemons.gif";
